sudo: false
cache:
  directories:
    - "node_modules"
language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: validity
      name: "Linting"
      script: npm run lint
    - stage: validity
      name: "Unit tests"
      script: npm run test-coverage && npm run report-coverage
    - stage: compile&test-e2e
      script: npm run test-e2e-latest
